---
abstract: 'modify attributes of symlinks without dereferencing them'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Module::Build: 0
  Module::Build::Compat: 0
  Test::More: 0
configure_requires:
  ExtUtils::CChecker: 0
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-lchown
provides:
  File::lchown:
    file: lib/File/lchown.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
